// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QRganize.Infrastructure.Data;

#nullable disable

namespace QRganize.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QRganize.Core.Entities.Comic", b =>
                {
                    b.Property<int>("ComicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comic_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComicId"));

                    b.Property<string>("AlternativeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alternative_title");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cover_image_path");

                    b.Property<int?>("CoverPageId")
                        .HasColumnType("integer")
                        .HasColumnName("cover_page_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ManagedPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("managed_path");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ComicId");

                    b.HasIndex("CoverPageId");

                    b.ToTable("comic", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.ComicCreator", b =>
                {
                    b.Property<int>("ComicId")
                        .HasColumnType("integer")
                        .HasColumnName("comic_id");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.HasKey("ComicId", "CreatorId");

                    b.HasIndex("CreatorId");

                    b.ToTable("comic_creator", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.ComicSource", b =>
                {
                    b.Property<int>("ComicId")
                        .HasColumnType("integer")
                        .HasColumnName("comic_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("ComicId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("comic_source", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.ComicTag", b =>
                {
                    b.Property<int>("ComicId")
                        .HasColumnType("integer")
                        .HasColumnName("comic_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("ComicId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("comic_tag", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.Creator", b =>
                {
                    b.Property<int>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreatorId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<string>("SocialLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("social_link");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("CreatorId");

                    b.ToTable("creator", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.DownloadSource", b =>
                {
                    b.Property<int>("DownloadSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("download_source_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DownloadSourceId"));

                    b.Property<string>("AuthorHandle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_handle");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<string>("PostId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("post_id");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.HasKey("DownloadSourceId");

                    b.ToTable("download_source", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.Engine", b =>
                {
                    b.Property<int>("EngineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("engine_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EngineId"));

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_endpoint");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("Configuration")
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EngineId");

                    b.ToTable("engine", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.EngineHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("EngineId")
                        .HasColumnType("integer")
                        .HasColumnName("engine_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("OriginalText")
                        .HasColumnType("text")
                        .HasColumnName("original_text");

                    b.Property<int?>("OverlayBoxId")
                        .HasColumnType("integer")
                        .HasColumnName("overlay_box_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("text")
                        .HasColumnName("translated_text");

                    b.HasKey("HistoryId");

                    b.HasIndex("EngineId");

                    b.HasIndex("OverlayBoxId");

                    b.ToTable("engine_history", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.OverlayBox", b =>
                {
                    b.Property<int>("OverlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("overlay_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OverlayId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("OriginalText")
                        .HasColumnType("text")
                        .HasColumnName("original_text");

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("page_id");

                    b.Property<double>("Rotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("rotation");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("text")
                        .HasColumnName("translated_text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.Property<int>("ZIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("z_index");

                    b.HasKey("OverlayId");

                    b.HasIndex("PageId");

                    b.ToTable("overlay_box", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("page_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PageId"));

                    b.Property<string>("ColorProfile")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color_profile");

                    b.Property<int>("ComicId")
                        .HasColumnType("integer")
                        .HasColumnName("comic_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Dpi")
                        .HasColumnType("integer")
                        .HasColumnName("dpi");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<int?>("FileSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ImageHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("image_hash");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail_path");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("PageId");

                    b.HasIndex("ComicId");

                    b.ToTable("page", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SourceId"));

                    b.Property<string>("AuthorHandle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_handle");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<string>("PostId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("post_id");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.HasKey("SourceId");

                    b.ToTable("source", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_sensitive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("TagId");

                    b.HasIndex("GroupId");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.TagGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("GroupId");

                    b.ToTable("tag_group", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.TextStyle", b =>
                {
                    b.Property<int>("TextStyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("text_style_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TextStyleId"));

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("background_color");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("font_family");

                    b.Property<double>("FontSize")
                        .HasColumnType("double precision")
                        .HasColumnName("font_size");

                    b.Property<string>("FontStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("normal")
                        .HasColumnName("font_style");

                    b.Property<string>("FontWeight")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("normal")
                        .HasColumnName("font_weight");

                    b.Property<double?>("LetterSpacing")
                        .HasColumnType("double precision")
                        .HasColumnName("letter_spacing");

                    b.Property<double?>("LineHeight")
                        .HasColumnType("double precision")
                        .HasColumnName("line_height");

                    b.Property<string>("TextAlign")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("text_align");

                    b.HasKey("TextStyleId");

                    b.ToTable("text_style", (string)null);
                });

            modelBuilder.Entity("QRganize.Core.Entities.Comic", b =>
                {
                    b.HasOne("QRganize.Core.Entities.Page", "CoverPage")
                        .WithMany()
                        .HasForeignKey("CoverPageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoverPage");
                });

            modelBuilder.Entity("QRganize.Core.Entities.ComicCreator", b =>
                {
                    b.HasOne("QRganize.Core.Entities.Comic", "Comic")
                        .WithMany("ComicCreators")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRganize.Core.Entities.Creator", "Creator")
                        .WithMany("ComicCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("QRganize.Core.Entities.ComicSource", b =>
                {
                    b.HasOne("QRganize.Core.Entities.Comic", "Comic")
                        .WithMany("ComicSources")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRganize.Core.Entities.Source", "Source")
                        .WithMany("ComicSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("QRganize.Core.Entities.ComicTag", b =>
                {
                    b.HasOne("QRganize.Core.Entities.Comic", "Comic")
                        .WithMany("ComicTags")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRganize.Core.Entities.Tag", "Tag")
                        .WithMany("ComicTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("QRganize.Core.Entities.EngineHistory", b =>
                {
                    b.HasOne("QRganize.Core.Entities.Engine", "Engine")
                        .WithMany("EngineHistories")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QRganize.Core.Entities.OverlayBox", "OverlayBox")
                        .WithMany()
                        .HasForeignKey("OverlayBoxId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Engine");

                    b.Navigation("OverlayBox");
                });

            modelBuilder.Entity("QRganize.Core.Entities.OverlayBox", b =>
                {
                    b.HasOne("QRganize.Core.Entities.Page", "Page")
                        .WithMany("OverlayBoxes")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("QRganize.Core.Entities.Page", b =>
                {
                    b.HasOne("QRganize.Core.Entities.Comic", "Comic")
                        .WithMany("Pages")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("QRganize.Core.Entities.Tag", b =>
                {
                    b.HasOne("QRganize.Core.Entities.TagGroup", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("QRganize.Core.Entities.Comic", b =>
                {
                    b.Navigation("ComicCreators");

                    b.Navigation("ComicSources");

                    b.Navigation("ComicTags");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("QRganize.Core.Entities.Creator", b =>
                {
                    b.Navigation("ComicCreators");
                });

            modelBuilder.Entity("QRganize.Core.Entities.Engine", b =>
                {
                    b.Navigation("EngineHistories");
                });

            modelBuilder.Entity("QRganize.Core.Entities.Page", b =>
                {
                    b.Navigation("OverlayBoxes");
                });

            modelBuilder.Entity("QRganize.Core.Entities.Source", b =>
                {
                    b.Navigation("ComicSources");
                });

            modelBuilder.Entity("QRganize.Core.Entities.Tag", b =>
                {
                    b.Navigation("ComicTags");
                });

            modelBuilder.Entity("QRganize.Core.Entities.TagGroup", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
